
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author andrescruz
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        tablasOrigen.add("countries");
        tablasOrigen.add("departments");
        tablasOrigen.add("employees");
        tablasOrigen.add("job_history");
        tablasOrigen.add("jobs");
        tablasOrigen.add("locations");
        tablasOrigen.add("regions");
        DefaultListModel modelo = (DefaultListModel) jl_sinReplicar.getModel();
                for (int i = 0; i < tablasOrigen.size(); i++) {
                    modelo.addElement(tablasOrigen.get(i));
                }
                
                jl_sinReplicar.setModel(modelo);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    public void setLista(DefaultListModel modelo, JList lista) {

    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_configuracion = new javax.swing.JDialog();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tf_nombreInstanciaOrigen = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf_nombreBDOrigen = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tf_puertoOrigen = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tf_nombreUsuarioOrigen = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tf_passwordOrigen = new javax.swing.JTextField();
        jb_probarOrigen = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        ta_OrigenPrueba = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jb_probarDestino = new javax.swing.JButton();
        tf_passwordDestino = new javax.swing.JTextField();
        tf_nombreUsuarioDestino = new javax.swing.JTextField();
        tf_puertoDestino = new javax.swing.JTextField();
        tf_nombreBDDestino = new javax.swing.JTextField();
        tf_nombreInstanciaDestino = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        ta_DestinoPrueba = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jb_guardar = new javax.swing.JButton();
        jb_regresarConfiguracion = new javax.swing.JButton();
        jd_replicar = new javax.swing.JDialog();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_sinReplicar = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_replicando = new javax.swing.JList<>();
        jb_replicar = new javax.swing.JButton();
        jb_noReplicar = new javax.swing.JButton();
        jb_guardarReplicar = new javax.swing.JButton();
        jb_regresar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jta_actualizaciones = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jb_configuracion = new javax.swing.JButton();
        jb_Salir = new javax.swing.JButton();

        jd_configuracion.setTitle("Configuración de Bases de Datos");

        jLabel3.setText("Nombre Instancia");

        tf_nombreInstanciaOrigen.setText("origen.cw9v0mt6g20g.us-east-1.rds.amazonaws.com");

        jLabel4.setText("Nombre Base de Datos");

        tf_nombreBDOrigen.setText("origen");

        jLabel5.setText("Puerto");

        tf_puertoOrigen.setText("5432");

        jLabel6.setText("Nombre usuario");

        tf_nombreUsuarioOrigen.setText("postgreadmin");

        jLabel7.setText("Password");

        tf_passwordOrigen.setText("password");

        jb_probarOrigen.setText("Probar");
        jb_probarOrigen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_probarOrigenMouseClicked(evt);
            }
        });

        ta_OrigenPrueba.setEditable(false);
        ta_OrigenPrueba.setColumns(20);
        ta_OrigenPrueba.setRows(5);
        jScrollPane4.setViewportView(ta_OrigenPrueba);

        jLabel16.setText("Resultado prueba:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_passwordOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_nombreUsuarioOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_puertoOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_nombreBDOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_nombreInstanciaOrigen, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jb_probarOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_nombreInstanciaOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_nombreBDOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_puertoOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_nombreUsuarioOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_passwordOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_probarOrigen, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jTabbedPane1.addTab("Base de Datos Origen", jPanel1);

        jLabel8.setText("Nombre Instancia");

        jLabel9.setText("Nombre Base de Datos");

        jLabel10.setText("Puerto");

        jLabel11.setText("Nombre usuario");

        jLabel12.setText("Password");

        jb_probarDestino.setText("Probar");
        jb_probarDestino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_probarDestinoMouseClicked(evt);
            }
        });

        tf_passwordDestino.setText("hr123");

        tf_nombreUsuarioDestino.setText("hr");

        tf_puertoDestino.setText("1521");

        tf_nombreBDDestino.setText("destino");

        tf_nombreInstanciaDestino.setText("destino.cw9v0mt6g20g.us-east-1.rds.amazonaws.com");

        ta_DestinoPrueba.setEditable(false);
        ta_DestinoPrueba.setColumns(20);
        ta_DestinoPrueba.setRows(5);
        jScrollPane5.setViewportView(ta_DestinoPrueba);

        jLabel17.setText("Resultado prueba:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_passwordDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_nombreUsuarioDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_puertoDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_nombreBDDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_nombreInstanciaDestino, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jb_probarDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_nombreInstanciaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tf_nombreBDDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tf_puertoDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tf_nombreUsuarioDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tf_passwordDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_probarDestino, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Base de datos Destino", jPanel2);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Configuración de Bases de Datos");

        jb_guardar.setText("Guardar");
        jb_guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_guardarMouseClicked(evt);
            }
        });

        jb_regresarConfiguracion.setText("Regresar");
        jb_regresarConfiguracion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_regresarConfiguracionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_configuracionLayout = new javax.swing.GroupLayout(jd_configuracion.getContentPane());
        jd_configuracion.getContentPane().setLayout(jd_configuracionLayout);
        jd_configuracionLayout.setHorizontalGroup(
            jd_configuracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(jd_configuracionLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jb_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jb_regresarConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd_configuracionLayout.setVerticalGroup(
            jd_configuracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_configuracionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_configuracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_guardar)
                    .addComponent(jb_regresarConfiguracion))
                .addGap(23, 23, 23))
        );

        jd_replicar.setTitle("Replicar Tablas");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Tablas BD Origen");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel14.setText("Sin Replicar");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel15.setText("Replicando");

        jl_sinReplicar.setModel(new DefaultListModel());
        jl_sinReplicar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_sinReplicarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jl_sinReplicar);

        jl_replicando.setModel(new DefaultListModel());
        jl_replicando.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_replicandoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jl_replicando);

        jb_replicar.setText(">>");
        jb_replicar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_replicarMouseClicked(evt);
            }
        });

        jb_noReplicar.setText("<<");
        jb_noReplicar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_noReplicarMouseClicked(evt);
            }
        });

        jb_guardarReplicar.setText("Guardar");
        jb_guardarReplicar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_guardarReplicarMouseClicked(evt);
            }
        });

        jb_regresar.setText("Regresar");
        jb_regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_regresarMouseClicked(evt);
            }
        });

        jta_actualizaciones.setColumns(20);
        jta_actualizaciones.setRows(5);
        jScrollPane3.setViewportView(jta_actualizaciones);

        javax.swing.GroupLayout jd_replicarLayout = new javax.swing.GroupLayout(jd_replicar.getContentPane());
        jd_replicar.getContentPane().setLayout(jd_replicarLayout);
        jd_replicarLayout.setHorizontalGroup(
            jd_replicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_replicarLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(96, 96, 96))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_replicarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jb_regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
            .addGroup(jd_replicarLayout.createSequentialGroup()
                .addGroup(jd_replicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_replicarLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jd_replicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jb_replicar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_noReplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_guardarReplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_replicarLayout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jLabel13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_replicarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jd_replicarLayout.setVerticalGroup(
            jd_replicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_replicarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(jd_replicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(jd_replicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_replicarLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jd_replicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jd_replicarLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jb_replicar)
                        .addGap(26, 26, 26)
                        .addComponent(jb_noReplicar)))
                .addGap(20, 20, 20)
                .addComponent(jb_guardarReplicar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jb_regresar)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel1.setText("Menú");

        jb_configuracion.setText("Configuración de base de datos");
        jb_configuracion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_configuracionMouseClicked(evt);
            }
        });

        jb_Salir.setText("Salir");
        jb_Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_SalirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jb_configuracion)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jb_configuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jb_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_configuracionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_configuracionMouseClicked
        jd_configuracion.pack();
        jd_configuracion.setModal(true);
        jd_configuracion.setLocationRelativeTo(this);
        jd_configuracion.setVisible(true);
    }//GEN-LAST:event_jb_configuracionMouseClicked

    private void jb_SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_SalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jb_SalirMouseClicked

    private void jb_regresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_regresarMouseClicked
        jta_actualizaciones.setText("");
        origen.cerrarConexion();
        destino.cerrarConexion();
        jd_replicar.setVisible(false);
    }//GEN-LAST:event_jb_regresarMouseClicked

    private void jb_regresarConfiguracionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_regresarConfiguracionMouseClicked
        ta_DestinoPrueba.setText("");
        ta_OrigenPrueba.setText("");
        jd_configuracion.setVisible(false);
    }//GEN-LAST:event_jb_regresarConfiguracionMouseClicked

    private void jl_sinReplicarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_sinReplicarMouseClicked
        if (jl_sinReplicar.getSelectedIndex() >= 0) {
            posicionSR = jl_sinReplicar.getSelectedIndex();
        } else {
            posicionSR = -1;
        }
    }//GEN-LAST:event_jl_sinReplicarMouseClicked

    private void jb_replicarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_replicarMouseClicked
        if (posicionSR != -1) {
            DefaultListModel modelo = (DefaultListModel) jl_replicando.getModel();
            modelo.addElement(tablasOrigen.get(posicionSR));
            jl_replicando.setModel(modelo);
            tablasReplicar.add(tablasOrigen.get(posicionSR));
            tablasOrigen.remove(posicionSR);

            DefaultListModel modeloSinReplicar = (DefaultListModel) jl_sinReplicar.getModel();
            modeloSinReplicar.remove(posicionSR);
            jl_sinReplicar.setModel(modeloSinReplicar);
            posicionSR = -1;
        } else {
            JOptionPane.showMessageDialog(null, "No hay tabla seleccionada");
        }
    }//GEN-LAST:event_jb_replicarMouseClicked

    private void jl_replicandoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_replicandoMouseClicked
        if (jl_replicando.getSelectedIndex() >= 0) {
            posicionR = jl_replicando.getSelectedIndex();
        } else {
            posicionR = -1;
        }
    }//GEN-LAST:event_jl_replicandoMouseClicked

    private void jb_noReplicarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_noReplicarMouseClicked
        if (posicionR != -1) {
            DefaultListModel modelo = (DefaultListModel) jl_sinReplicar.getModel();
            modelo.addElement(tablasReplicar.get(posicionR));
            jl_sinReplicar.setModel(modelo);
            tablasOrigen.add(tablasReplicar.get(posicionR));
            tablasReplicar.remove(posicionR);
            DefaultListModel modeloReplicando = (DefaultListModel) jl_replicando.getModel();
            modeloReplicando.remove(posicionR);
            jl_replicando.setModel(modeloReplicando);
            posicionR = -1;
        } else {
            JOptionPane.showMessageDialog(null, "No hay tabla seleccionada");
        }
    }//GEN-LAST:event_jb_noReplicarMouseClicked

    private void jb_probarOrigenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_probarOrigenMouseClicked
        // TODO add your handling code here:
        try {
            Postgre prueba = new Postgre(tf_nombreInstanciaOrigen, tf_nombreBDOrigen, tf_puertoOrigen, tf_nombreUsuarioOrigen, tf_passwordOrigen, ta_OrigenPrueba, jta_actualizaciones);
            prueba.setIsPrueba(true);
            prueba.crearConexion();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jb_probarOrigenMouseClicked

    private void jb_probarDestinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_probarDestinoMouseClicked
        // TODO add your handling code here:
        try {
            Oracle prueba = new Oracle(tf_nombreInstanciaDestino, tf_nombreBDDestino, tf_puertoDestino, tf_nombreUsuarioDestino, tf_passwordDestino, ta_DestinoPrueba, jta_actualizaciones);
            prueba.setIsPrueba(true);
            prueba.crearConexion();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jb_probarDestinoMouseClicked

    private void jb_guardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_guardarMouseClicked
        // TODO add your handling code here:
        origen =new Postgre(tf_nombreInstanciaOrigen, tf_nombreBDOrigen, tf_puertoOrigen, tf_nombreUsuarioOrigen, tf_passwordOrigen, ta_OrigenPrueba, jta_actualizaciones);
        origen.crearConexion();
        destino= new Oracle(tf_nombreInstanciaDestino, tf_nombreBDDestino, tf_puertoDestino, tf_nombreUsuarioDestino, tf_passwordDestino, ta_DestinoPrueba, jta_actualizaciones);
        destino.crearConexion();
        try {
            if (origen.estadoConexion()&&destino.estadoConexion()) {
                jd_replicar.pack();
                jd_replicar.setModal(true);
                jd_replicar.setLocationRelativeTo(this);
                jd_replicar.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null, "Ocurrio un error con una o ambas conexiones...\nRevise la informacion y haga las pruebas respectivas para poder guardar y replicar.");
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jb_guardarMouseClicked

    private void jb_guardarReplicarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_guardarReplicarMouseClicked
        // TODO add your handling code here:
        DefaultListModel modelo= (DefaultListModel)jl_replicando.getModel();
        if (!modelo.isEmpty()) {
            jta_actualizaciones.append("\n-------------Nueva Sincronizacion-------------");
            for (int i = 0; i < modelo.size(); i++) {
                String tablamodelo = modelo.get(i).toString();
                String condicion="";
                if (origen.cargarTablas() && origen.getTabla(tablamodelo) != null) {
                    condicion += "AND tabla = '" + tablamodelo + "'";
                } else {
                    condicion += "WHERE tabla = '" + tablamodelo + "'";
                }
                if (origen.generadorQuery(condicion, tablamodelo)) {
                    boolean fallo=false;
                    ArrayList<String> diferencias = origen.getDiferencias();
                    for(String diferencia:diferencias){
                        if (!destino.generarCambios(diferencia)) {
                            fallo = true;
                            break;
                        }
                    }
                    if (!fallo) {
                        origen.setFechaActualizacion(tablamodelo, new Date());
                        jta_actualizaciones.append("\nSe han actualizado los datos de la tabla "+ tablamodelo+": "+ origen.getFechaActualizacion(tablamodelo)+" GMT");
                        jta_actualizaciones.append("\n--------------------------------------------------------");
                        jta_actualizaciones.append("\nSincronizacion realizada entre bases de Datos");
                        jta_actualizaciones.append("\n--------------------------------------------------------");
                        origen.guardarTablas();
                    }
                }
            }
        }else{
            JOptionPane.showMessageDialog(null,"No hay tabla seleccionada en Replicando");
        }
    }//GEN-LAST:event_jb_guardarReplicarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jb_Salir;
    private javax.swing.JButton jb_configuracion;
    private javax.swing.JButton jb_guardar;
    private javax.swing.JButton jb_guardarReplicar;
    private javax.swing.JButton jb_noReplicar;
    private javax.swing.JButton jb_probarDestino;
    private javax.swing.JButton jb_probarOrigen;
    private javax.swing.JButton jb_regresar;
    private javax.swing.JButton jb_regresarConfiguracion;
    private javax.swing.JButton jb_replicar;
    private javax.swing.JDialog jd_configuracion;
    private javax.swing.JDialog jd_replicar;
    private javax.swing.JList<String> jl_replicando;
    private javax.swing.JList<String> jl_sinReplicar;
    private javax.swing.JTextArea jta_actualizaciones;
    private javax.swing.JTextArea ta_DestinoPrueba;
    private javax.swing.JTextArea ta_OrigenPrueba;
    private javax.swing.JTextField tf_nombreBDDestino;
    private javax.swing.JTextField tf_nombreBDOrigen;
    private javax.swing.JTextField tf_nombreInstanciaDestino;
    private javax.swing.JTextField tf_nombreInstanciaOrigen;
    private javax.swing.JTextField tf_nombreUsuarioDestino;
    private javax.swing.JTextField tf_nombreUsuarioOrigen;
    private javax.swing.JTextField tf_passwordDestino;
    private javax.swing.JTextField tf_passwordOrigen;
    private javax.swing.JTextField tf_puertoDestino;
    private javax.swing.JTextField tf_puertoOrigen;
    // End of variables declaration//GEN-END:variables
    ArrayList<String> tablasOrigen = new ArrayList();
    ArrayList<String> tablasReplicar = new ArrayList();
    int posicionSR = -1, posicionR = -1;
    Postgre origen=null;
    Oracle destino=null;
}
